### ISSUE TITLE
Is there a Docker container I can reference?

### ISSUE THREAD

**Issue by jonathanlaniado** [jamjnsn/cartridge#1]
Right now the error I get from Docker is:

`Failed to deploy a stack: Pulling cartridge (jamjnsn/cartridge:) The image for the service you're trying to recreate has been removed. If you continue, volume data could be lost. Consider backing up your data before continuing. pull access denied for jamjnsn/cartridge, repository does not exist or may require 'docker login': denied: requested access to the resource is denied : exit status 1`

**Comment by jamjnsn** [comment]
This is currently a work-in-progress. Not quite ready for use. Once I've added basic administration (library and user management) I'll overhaul the readme and get a Docker image pushed. Thanks for your interest!

**Comment by zblesk** [comment]
Once that's ready, do you plan to use the GH's Releases feature? 

I'd like to keep an eye on this project, which I usually do by subscribing the Releases RSS, but I'm not sure if anything will eventually be there, or if you have other plans.

**Comment by jamjnsn** [comment]
> Once that's ready, do you plan to use the GH's Releases feature?
> 
> I'd like to keep an eye on this project, which I usually do by subscribing the Releases RSS, but I'm not sure if anything will eventually be there, or if you have other plans.

I'm not super familiar with most Github features, but the goal will be to utilize these features as much as possible where appropriate. I'll just need to look into it. I haven't had time for work on this lately, but I'm hoping to finish up the last little bit needed for an alpha release within the next couple of weeks.

**Comment by pepitoria** [comment]
> I'm hoping to finish up the last little bit needed for an alpha release within the next couple of weeks.

Nice! looking forward to trying this!
