### ISSUE TITLE
Dockerhub image?

### ISSUE THREAD

**Issue by CorneliousJD** [jamjnsn/cartridge#2]
Sorry for opening an issue here - is there a dockerhub image of Cartridge? I'd like to fire it up and give it a spin to see what it's about.
it seems like a great starting ground for a "game collection management" software akin to HowLongToBeat and/or Backloggery, or others, but open source and self-hosted, which a lot of people are after!

If there's a dockerhub image I can deploy this to a lot more people via unRAID's Community Apps too and get more people interested hopefully.

**Comment by jamjnsn** [comment]
I definitely appreciate the interest. This isn't currently quite ready to spin up for testing. Most of the groundwork is in, but I still need to make a UI to manage the collection and fix game matches. Currently the only way to match games is the exact ROM title with the directory being used to identify platforms. I wish I could give a timeline but it's been difficult to put in the work recently. Hopefully I'll have something rolling along soon!
